### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount":100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount":100
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "8e99662991aa4bef8e48686f9607e2b0",
  "accountNumber": "1000000002",
  "amount":100
}

### query transaction
GET http://localhost:8080/transaction/6b4c7f21e8944650ba99cd41afdf8d26